### ISSUE TITLE
Switch from s3deploy to Hugo Deploy?

### ISSUE THREAD

**Issue by parsiya** [parsiya/parsiya.net#53]
Hugo has its own deploy thingie. If I can use it then I can remove s3deploy from my workflow. Seems like I can just directly deploy to an S3 bucket. But I wonder if it has the caching/gzip options that s3deploy has.

On a side note, maybe bep wrote that, too. In which case, the features might be similar. 

Info: https://gohugo.io/hosting-and-deployment/hugo-deploy/

Edit: It appears that the functionality is very similar. Here's the sample file from the link above (converted to yaml):

```yaml
deployment:
  order: # do I really need this?
    - .jpg$
    - .gif$
  targets:
    - name: mydeployment
      cloudFrontDistributionID: 2222
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
```

**BUT** the tool assumes we have logged in and configured the AWS cli tools. So we cannot just give the AWS key and secret to it.

EDIT: We might be able to pass it to the tool via env variables set via Github secrets. These are already added to the repository, we just need to assign them to env variables in the pipeline.
